spring.application.name=queueless

server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ? IMPORTANT: plain string (no base64 headache)
jwt.secret=${JWT_SECRET:my-super-secret-key-123456789}

spring.jpa.hibernate.ddl-auto=update