spring.application.name=queueless
# Let Render assign the port automatically
server.port=${PORT:8080}

# Connect to the Render Database using Environment Variables
spring.datasource.url=jdbc:postgresql://dpg-d7i9241kh4rs73ar56o0-a:5432/queueless_db_frs9
spring.datasource.username=queueless_db_frs9_user
spring.datasource.password=7CGgQ38oATuwIxTDnmACmXNjdX3GyykA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect